1-notification and 2-sortable-table-v1
js-tasks-ru/js-20210806_elena-ilyukhina pull request #5
Opened 2021-08-24 16:22 UTC by astro-snail

Solutions for 1-notification and 2-sortable-table-v1

2021-08-24 16:24 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-24 21:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2021-08-26 19:25 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-26 19:57 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    if (!NotificationMessage.isRunning) {
а как же логика удаления? Ведь нам нужно удалить предыдущий элемент когда мы показываем текущий...

2021-08-26 19:58 UTC, dosandk requested changes
решение `NotificationMessage` необходимо поправить - добавить логику удаления предыдущего нотификейшена

2021-08-26 21:00 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-27 14:28 UTC, dosandk approved these changes
good 👍 хорошие решения

2021-08-27 14:28 UTC, merged